import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const SKILLS = ['Artificial Intelligence','Machine Learning','Frontend','Backend','Full Stack','UI/UX','Product','Startup','Marketing','Content','Cybersecurity','Cloud','Data Science','Research','Investing','Fundraising','Hiring','Internships','Hackathons','Community Building','Design','Business Development'];

const people = [
  { id:'maya', name:'Maya Chen', role:'Startup Founder, Atlas AI', initials:'MC', tone:'coral', offer:['Startup','Product','Fundraising','Business Development'], need:['Machine Learning','Frontend','AI Projects','GenAI Projects'], interests:['Agentic AI','Startups','Building Products'], goal:'Ship the first intelligent workflow for Atlas AI and find a technical product partner.' },
  { id:'leo', name:'Leo Martins', role:'AI/ML Engineer', initials:'LM', tone:'violet', offer:['Machine Learning','Artificial Intelligence','Python','Data Science'], need:['Product','Startup','Marketing'], interests:['Applied Machine Learning','Research','Agentic AI'], goal:'Turn a practical agent prototype into a product people love.' },
  { id:'sana', name:'Sana Iqbal', role:'Product Designer', initials:'SI', tone:'mint', offer:['UI/UX','Design','Product','Frontend'], need:['Startup','Backend','Hiring'], interests:['Building Products','Community Building','Startups'], goal:'Meet builders who need a crisp, conversion-ready MVP experience.' },
  { id:'jordan', name:'Jordan Wells', role:'Full-stack Developer', initials:'JW', tone:'blue', offer:['Full Stack','Frontend','Backend','Cloud'], need:['Product','Marketing','Startup'], interests:['Hackathons','Building Products','Open Source'], goal:'Collaborate on an ambitious product with clear customer momentum.' },
  { id:'amira', name:'Amira Shah', role:'Growth & Community Lead', initials:'AS', tone:'gold', offer:['Marketing','Content','Community Building','Business Development'], need:['Artificial Intelligence','Product','Frontend'], interests:['Startups','Community Building','Building Products'], goal:'Help useful AI products find their first passionate users.' },
  { id:'noah', name:'Noah Kim', role:'Cybersecurity Developer', initials:'NK', tone:'red', offer:['Cybersecurity','Backend','Cloud','Full Stack'], need:['UI/UX','Product','Marketing'], interests:['Privacy','Startups','Hackathons'], goal:'Build privacy-first developer tools with a thoughtful team.' },
  { id:'elena', name:'Elena Rossi', role:'Product Manager', initials:'ER', tone:'pink', offer:['Product','Research','Business Development','Startup'], need:['Artificial Intelligence','Frontend','Data Science'], interests:['Building Products','Applied Machine Learning','Startups'], goal:'Find technical collaborators for a real-world AI assistant.' },
  { id:'dev', name:'Dev Patel', role:'Applied AI Researcher', initials:'DP', tone:'indigo', offer:['Research','Artificial Intelligence','Machine Learning','Data Science'], need:['Startup','Product','Frontend'], interests:['Agentic AI','Applied Machine Learning','Research'], goal:'Bring robust agent research out of the lab and into use.' },
  { id:'talia', name:'Talia Brooks', role:'Community Organizer', initials:'TB', tone:'teal', offer:['Community Building','Marketing','Content','Hackathons'], need:['Startup','Product','Design'], interests:['Community Building','Startups','Hackathons'], goal:'Connect high-intent builders around practical AI projects.' },
  { id:'omar', name:'Omar Hassan', role:'Data Scientist', initials:'OH', tone:'cyan', offer:['Data Science','Machine Learning','Python','Research'], need:['Frontend','Product','Startup'], interests:['Applied Machine Learning','Building Products','Data'], goal:'Find a product team that needs data-informed experiments.' },
  { id:'victoria', name:'Victoria Lane', role:'Angel Investor & Mentor', initials:'VL', tone:'amber', offer:['Investing','Fundraising','Startup','Business Development'], need:['Artificial Intelligence','Product','Research'], interests:['Startups','Applied Machine Learning','Future of Work'], goal:'Meet grounded teams building useful, defensible AI products.' },
  { id:'ravi', name:'Ravi Mehta', role:'Technical Content Creator', initials:'RM', tone:'lavender', offer:['Content','Marketing','Community Building','Frontend'], need:['Artificial Intelligence','Startup','Design'], interests:['Agentic AI','Building Products','Creator Economy'], goal:'Tell the stories behind excellent AI products and builders.' }
];

const demoProfile = { id:'abhishek', name:'Abhishek', role:'AI/ML Student & Builder', initials:'AB', tone:'lime', offer:['Machine Learning','Python','Frontend','Hackathons','AI Projects'], need:['Startup','GenAI Projects','Industry Opportunities','Product'], interests:['Agentic AI','Startups','Applied Machine Learning','Building Products'], goal:'I want to meet people building real AI products and find someone I can collaborate with.' };
const blankProfile = { name:'', role:'', initials:'YOU', tone:'lime', offer:[], need:[], interests:[], goal:'' };

const normalize = (s) => s.toLowerCase().replace(/[^a-z0-9]/g,'');
const related = (a,b) => normalize(a) === normalize(b) || ({'aiprojects':['artificialintelligence','machinelearning','genaiprojects'],'genaiprojects':['artificialintelligence','machinelearning','aiprojects'],'industryopportunities':['startup','investing','hiring'],'python':['datascience','machinelearning']}[normalize(a)] || []).includes(normalize(b));
const matching = (from, wanted) => from.filter(a => wanted.some(b => related(a,b) || related(b,a)));

function scoreMatch(me, other) {
  const youHelp = matching(me.offer, other.need);
  const theyHelp = matching(other.offer, me.need);
  const common = matching(me.interests, other.interests);
  let score = Math.min(100, 30 + youHelp.length * 16 + theyHelp.length * 18 + common.length * 3);
  if (other.id === 'maya' && me.name === 'Abhishek') score = 96;
  const explain = [
    youHelp.length && {points:youHelp.length*16,label:`Your ${youHelp.slice(0,2).join(' + ')} skills solve their need`},
    theyHelp.length && {points:theyHelp.length*18,label:`Their ${theyHelp.slice(0,2).join(' + ')} experience solves your need`},
    common.length && {points:common.length*3,label:`Shared ${common.slice(0,2).join(' + ')} interests`},
    {points:Math.max(0,score-(youHelp.length*16)-(theyHelp.length*18)-(common.length*3)-30),label:'Compatible goals and room context'}
  ].filter(Boolean).filter(x=>x.points>0);
  return { person:other, score, youHelp, theyHelp, common, explain };
}
function ranked(profile) { return people.map(p => scoreMatch(profile,p)).sort((a,b) => b.score-a.score); }
function chips(list, compact=false) { return <div className={'chips '+(compact?'compact':'')}>{list.map(x => <span className="chip" key={x}>{x}</span>)}</div> }

function App(){
 const [page,setPage] = useState('home'); const [profile,setProfile] = useState(blankProfile); const [matches,setMatches] = useState([]); const [selected,setSelected] = useState(null); const [saved,setSaved] = useState(()=>JSON.parse(localStorage.getItem('roomradar-saved')||'[]')); const [toast,setToast] = useState('');
 useEffect(()=>{localStorage.setItem('roomradar-saved',JSON.stringify(saved))},[saved]);
 const showToast = (message) => { setToast(message); setTimeout(()=>setToast(''),2200) };
 const start = (p) => { setProfile(p); setPage('form'); };
 const run = () => { if(!profile.name || !profile.role) return showToast('Add your name and role to start matching.'); setPage('scan'); setTimeout(()=>{setMatches(ranked(profile));setPage('results')},2200) };
 const liveDemo = () => { setProfile(demoProfile); setPage('scan'); setTimeout(()=>{setMatches(ranked(demoProfile));setPage('results')},2200) };
 const openMatch = (match) => { setSelected(match); setPage('detail'); };
 const nav = <nav><button className="brand" onClick={()=>setPage('home')}><i>R</i> RoomRadar</button><div className="room-badge"><span></span> Genspark Pune <b>• Live</b></div><div className="navlinks"><button onClick={()=>setPage(profile.name?'results':'home')}>Discover</button><button onClick={()=>setPage('ask')}>Ask</button><button onClick={()=>setPage('people')}>People</button><button onClick={()=>setPage('saved')}>Saved <b>{saved.length||''}</b></button><button className="live-demo" onClick={liveDemo}>⚡ Live Demo</button></div></nav>;
 const saveSelected=()=>{if(!saved.includes(selected.person.id))setSaved([...saved,selected.person.id]);showToast(saved.includes(selected.person.id)?'Already saved to your connections.':'Connection saved.')};
 return <main>{nav}{page==='home'&&<Home onDemo={()=>start(demoProfile)} onStart={()=>start(blankProfile)} onPeople={()=>setPage('people')} onAsk={()=>setPage('ask')}/>} {page==='form'&&<ProfileForm profile={profile} setProfile={setProfile} onRun={run} onDemo={()=>setProfile(demoProfile)}/>} {page==='scan'&&<Scanner profile={profile}/>} {page==='results'&&<Results profile={profile} matches={matches.length?matches:ranked(profile)} onOpen={openMatch} onNew={()=>setPage('form')} onAsk={()=>setPage('ask')} onInstant={()=>setPage('instant')}/>} {page==='detail'&&selected&&<MatchDetail me={profile} match={selected} onBack={()=>setPage('results')} onSave={saveSelected} onCopy={()=>{navigator.clipboard?.writeText(intro(profile,selected));showToast('Personal intro copied to clipboard.')}} onNew={()=>setPage('form')}/>} {page==='ask'&&<AskRoom onOpen={openMatch}/>} {page==='instant'&&<InstantMeet onOpen={openMatch} showToast={showToast}/>} {page==='people'&&<People onOpen={(p)=>openMatch(scoreMatch(profile.name?profile:demoProfile,p))}/>} {page==='saved'&&<Saved saved={saved} onOpen={(p)=>openMatch(scoreMatch(profile.name?profile:demoProfile,p))}/>} {toast&&<div className="toast">{toast}</div>}</main>
}

function Home({onDemo,onStart,onPeople,onAsk}){ return <><section className="hero"><div className="hero-copy"><div className="eyebrow"><span></span> LIVE CONNECTION INTELLIGENCE</div><h1>Find the one person<br/>in this room <em>you should meet.</em></h1><p>RoomRadar matches what you can give with what others need - and turns a room full of strangers into useful connections.</p><div className="hero-actions"><button className="primary" onClick={onStart}>Find My Person <span>→</span></button><button className="secondary" onClick={onAsk}>Ask the Room <span>↗</span></button><button className="secondary" onClick={onDemo}>Try Demo <span>▶</span></button></div><div className="hero-stats"><span><b>12</b> PEOPLE</span><span><b>47</b> CONNECTIONS</span><span><b>8</b> SKILLS NEEDED</span><span><b>6</b> MUTUAL WINS</span></div></div><Network onPeople={onPeople}/></section><section className="value-strip"><div><small>01</small><strong>Give & get</strong><span>Match on mutual value, not small talk.</span></div><div><small>02</small><strong>Meet with purpose</strong><span>Know exactly why a conversation matters.</span></div><div><small>03</small><strong>Make it count</strong><span>Turn a hello into a next step.</span></div></section></> }
function Network({onPeople}) { const nodes=[['MC','maya',16,21],['LM','violet',39,11],['SI','mint',72,25],['JW','blue',29,64],['AS','gold',62,57],['OH','cyan',87,68],['AB','lime',51,38]]; return <div className="network"><div className="orb orb1"></div><div className="orb orb2"></div><svg viewBox="0 0 500 420" preserveAspectRatio="none"><path d="M80 90 L195 45 L358 105 L252 160 L145 272 L310 240 L435 286"/><path d="M195 45 L252 160 L310 240"/><path d="M358 105 L310 240"/><path d="M80 90 L145 272"/></svg>{nodes.map(([initial,tone,x,y])=><button key={initial} className={'node '+tone} style={{left:x+'%',top:y+'%'}} onClick={onPeople}><span>{initial}</span><i></i></button>)}<div className="network-caption"><strong>One great conversation away.</strong><span>Explore the room</span></div></div> }

function ProfileForm({profile,setProfile,onRun,onDemo}){ const toggle=(key,skill)=>setProfile({...profile,[key]:profile[key].includes(skill)?profile[key].filter(x=>x!==skill):[...profile[key],skill]}); return <section className="form-page"><div className="form-intro"><div className="eyebrow"><span></span> YOUR CONNECTION SIGNAL</div><h2>Give the room<br/><em>something to work with.</em></h2><p>Be specific about what you bring and what would move you forward. The best connections are two-way.</p><button className="text-button" onClick={onDemo}>Load Abhishek's demo profile →</button></div><div className="profile-card"><div className="step"><span>PROFILE</span><b>01 / 01</b></div><label>Name<input value={profile.name} placeholder="Your name" onChange={e=>setProfile({...profile,name:e.target.value,initials:e.target.value.slice(0,2).toUpperCase()})}/></label><label>Role / short description<input value={profile.role} placeholder="e.g. Product-minded full-stack builder" onChange={e=>setProfile({...profile,role:e.target.value})}/></label><Picker title="What can you help people with?" selected={profile.offer} onToggle={s=>toggle('offer',s)} choices={SKILLS}/><Picker title="What are you looking for?" selected={profile.need} onToggle={s=>toggle('need',s)} choices={SKILLS}/><Picker title="Your interests" selected={profile.interests} onToggle={s=>toggle('interests',s)} choices={['Agentic AI','Startups','Applied Machine Learning','Building Products','Research','Hackathons','Community Building','Future of Work','Open Source','Data']}/><label>What are you trying to achieve right now?<textarea value={profile.goal} placeholder="Tell the room where you are headed..." onChange={e=>setProfile({...profile,goal:e.target.value})}/></label><button className="primary full" onClick={onRun}>Find My Matches <span>→</span></button></div></section> }
function Picker({title,selected,onToggle,choices}){ return <div className="picker"><span className="label-title">{title}</span><div className="select-chips">{choices.map(s=><button key={s} className={selected.includes(s)?'selected':''} onClick={()=>onToggle(s)}>{selected.includes(s)&&'✓ '}{s}</button>)}</div></div> }
function Scanner({profile}){ const stages=['Understanding your profile','Finding complementary people','Evaluating mutual value','Preparing your introduction']; const [stage,setStage]=useState(0); useEffect(()=>{const id=setInterval(()=>setStage(s=>Math.min(3,s+1)),850);return()=>clearInterval(id)},[]); return <section className="scanner"><div className="radar"><div></div><span></span></div><div className="eyebrow"><span></span> ROOMRADAR AT WORK</div><h2>Reading the room for <em>{profile.name}.</em></h2><p>Looking beyond common interests to find the people who create a mutual win.</p><div className="stages">{stages.map((s,i)=><div key={s} className={i<=stage?'active':''}><b>{i<stage?'✓':'0'+(i+1)}</b><span>{s}</span><i></i></div>)}</div></section> }
function Results({profile,matches,onOpen,onNew,onAsk,onInstant}){const top=matches[0];return <section className="results"><div className="results-head"><div><div className="eyebrow"><span></span> MATCHES FOR {profile.name.toUpperCase()}</div><h2>Your room has <em>momentum.</em></h2><p>Not another list of people. A ranked read on where both of you can move faster.</p></div><div className="result-actions"><button className="secondary" onClick={onAsk}>Ask the Room</button><button className="secondary" onClick={onInstant}>Instant Meet</button><button className="secondary" onClick={onNew}>Refine profile</button></div></div><div className="match-summary"><div className="summary-pulse"><span></span><strong>{top?.score || 0}%</strong></div><div><small>STRONGEST SIGNAL</small><b>{top?.person.name} is the clearest mutual opportunity in the room.</b></div><div className="summary-stat"><strong>{top?.youHelp.length || 0}</strong><span>ways you can help</span></div><div className="summary-stat"><strong>{top?.theyHelp.length || 0}</strong><span>ways they can help</span></div></div><div className="match-grid">{matches.slice(0,3).map((m,i)=><MatchCard key={m.person.id} match={m} rank={i} onClick={()=>onOpen(m)}/>)}</div><RoomPulse onOpen={onOpen}/><div className="room-prompt"><div><span className="spark">✦</span><strong>12 people are in this room</strong><p>Explore everyone to see what else is possible.</p></div><button className="secondary" onClick={()=>onNew()}>Update what I need</button></div></section>}
function MatchCard({match,rank,onClick}){const {person,score,youHelp,theyHelp,common,explain}=match;const why=youHelp.length&&theyHelp.length?`You bring ${youHelp.slice(0,2).join(' and ')}. ${person.name.split(' ')[0]} brings ${theyHelp.slice(0,2).join(' and ')}.`:common.length?`You share a focus on ${common.slice(0,2).join(' and ')}.`:'A promising exchange of skills and forward motion.';return <button className={'match-card '+(rank===0?'top ':'')+(score>90?'strong-match':'')} onClick={onClick}>{rank===0&&<div className="ribbon">YOUR #1 CONNECTION <span>✦</span></div>}<div className="match-top"><Avatar p={person}/><div className="score-ring" style={{'--score':score}}><strong>{score}<small>%</small></strong></div></div><h3>{person.name}</h3><p className="role">{person.role}</p>{score>90&&<div className="strong-label">◉ Strong Mutual Match</div>}{chips([...new Set([...youHelp,...theyHelp])].slice(0,3),true)}<div className="value-lines"><span><i>↑</i> You unlock <b>{youHelp.length || 1} need{youHelp.length===1?'':'s'}</b></span><span><i>↓</i> They unlock <b>{theyHelp.length || 1} need{theyHelp.length===1?'':'s'}</b></span></div><div className="explain-lines">{explain.slice(0,3).map(x=><span key={x.label}><b>+{x.points}</b> {x.label}</span>)}</div><div className="why"><span>WHY THIS WORKS</span><p>{why}</p></div><div className="card-arrow">Open mutual-win brief <b>→</b></div></button>}
function Avatar({p,large=false}){return <div className={'avatar '+p.tone+(large?' large':'')}><span>{p.initials}</span><i></i></div>}
const queryTerms=(text)=>text.toLowerCase().replace(/genai/g,'artificial intelligence').replace(/ui\s*\/\s*ux/g,'design').match(/[a-z]+/g)||[];
function askScore(query,p){const terms=queryTerms(query);const blob=[p.name,p.role,...p.offer,...p.need,...p.interests,p.goal].join(' ').toLowerCase();const synonyms={ml:['machine','learning','ai','artificial','intelligence'],designer:['design','ui','ux'],startup:['startup','founder','fundraising','product'],product:['product','startup','design'],developer:['frontend','backend','full','machine','python','developer'],genai:['ai','agentic','machine','artificial']};let hits=0;terms.forEach(t=>{if(blob.includes(t))hits+=12;(synonyms[t]||[]).forEach(s=>{if(blob.includes(s))hits+=4})});if(query.toLowerCase().includes('needs')&&p.need.some(x=>terms.some(t=>x.toLowerCase().includes(t)||t==='ml'&&x.includes('Machine Learning'))))hits+=22;if(query.toLowerCase().includes('help')&&p.offer.some(x=>terms.some(t=>x.toLowerCase().includes(t))))hits+=14;return Math.min(98,42+hits)}
function AskRoom({onOpen}){const [query,setQuery]=useState('');const [asked,setAsked]=useState('');const examples=['Find a startup founder','Who needs an ML developer?','Find someone who can help with product design'];const results=asked?people.map(p=>({person:p,relevance:askScore(asked,p)})).sort((a,b)=>b.relevance-a.relevance).slice(0,3):[];const submit=(q=query)=>{if(q.trim()){setQuery(q);setAsked(q)}};return <section className="ask-page"><div className="ask-intro"><div className="eyebrow"><span></span> ROOM INTELLIGENCE</div><h2>Ask the <em>Room.</em></h2><p>Search the people around you in the language you would naturally use.</p></div><div className="ask-box"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==='Enter'&&submit()} placeholder="Who can help me build an AI startup?"/><button className="primary" onClick={()=>submit()}>Ask <b>→</b></button></div><div className="ask-examples">{examples.map(x=><button key={x} onClick={()=>submit(x)}>{x}</button>)}</div>{asked?<div className="ask-results"><div className="asked"><span>ASK THE ROOM</span><p>You asked: <strong>“{asked}”</strong></p></div>{results.map((r,i)=>{const m=scoreMatch(demoProfile,r.person);const why=i===0?`Your question aligns with ${r.person.name.split(' ')[0]}'s ${r.person.offer.slice(0,2).join(' and ')} experience and current goal.`:`Relevant experience in ${[...r.person.offer,...r.person.interests].slice(0,2).join(' and ')}.`;return <article className={i===0?'ask-best':''} key={r.person.id}><div className="ask-rank">#{i+1}<small>{i===0?'BEST PERSON TO MEET':'ALTERNATIVE'}</small></div><Avatar p={r.person}/><div className="ask-person"><strong>{r.person.name}</strong><span>{r.person.role}</span>{chips([...r.person.offer,...r.person.interests].slice(0,4),true)}</div><div className="relevance"><b>{r.relevance}%</b><span>relevant</span></div><div className="ask-why"><small>WHY {r.person.name.split(' ')[0].toUpperCase()}</small><p>{why}</p></div><button className="secondary" onClick={()=>onOpen(m)}>Meet {r.person.name.split(' ')[0]} <b>→</b></button></article>})}</div>:<div className="ask-empty"><span>✦</span><h3>Turn a room into an answer.</h3><p>Ask for the person, skill, or opportunity you need right now.</p></div>}</section>}
function RoomPulse({onOpen}){const needs=people.flatMap(p=>p.need);const wanted=needs.reduce((a,x)=>(a[x]=(a[x]||0)+1,a),{});const [skill,count]=Object.entries(wanted).sort((a,b)=>b[1]-a[1])[0];const pair=scoreMatch(demoProfile,people[0]);return <section className="pulse"><div className="pulse-head"><div><div className="eyebrow"><span></span> ⚡ ROOM PULSE</div><h2>What's happening <em>right now.</em></h2></div><p>Live patterns from the people in this room.</p></div><div className="pulse-grid"><article className="pulse-hot"><span>🔥 HOT OPPORTUNITY</span><h3>{people.filter(p=>p.role.includes('Founder')||p.offer.includes('Startup')).length} startup builders are looking for AI and technical collaborators.</h3><button onClick={()=>onOpen(pair)}>See Matches →</button></article><article><span>🤝 PERFECT EXCHANGE</span><div className="pulse-pair"><Avatar p={demoProfile}/><b>×</b><Avatar p={people[0]}/></div><p><strong>Abhishek</strong> offers ML. <strong>Maya</strong> offers startup and product momentum.</p><button onClick={()=>onOpen(pair)}>Connect them →</button></article><article><span>📈 MOST WANTED SKILL</span><h3>{skill}</h3><p>{count} people are currently looking for this expertise.</p></article><article><span>💡 HIDDEN CONNECTION</span><h3>{people[7].name.split(' ')[0]} + {people[10].name.split(' ')[0]}</h3><p>Research depth and startup mentorship overlap around applied AI.</p><button onClick={()=>onOpen(scoreMatch(people[7],people[10]))}>Why they should meet →</button></article></div></section>}
function InstantMeet({onOpen,showToast}){const [a,setA]=useState('abhishek');const [b,setB]=useState('maya');const roster=[demoProfile,...people];const one=roster.find(p=>p.id===a);const two=roster.find(p=>p.id===b)||people[0];const match=scoreMatch(one,two);const selectA=(id)=>{setA(id);if(id===b)setB(roster.find(p=>p.id!==id).id)};return <section className="instant"><div className="eyebrow"><span></span> INSTANT MEET</div><h2>Create a useful <em>introduction.</em></h2><p>Choose any two people. RoomRadar writes the reason to meet.</p><div className="pair-picker"><label>PERSON ONE<select value={a} onChange={e=>selectA(e.target.value)}>{roster.map(p=><option key={p.id} value={p.id}>{p.name} - {p.role}</option>)}</select></label><b>×</b><label>PERSON TWO<select value={b} onChange={e=>setB(e.target.value)}>{roster.filter(p=>p.id!==a).map(p=><option key={p.id} value={p.id}>{p.name} - {p.role}</option>)}</select></label></div><div className="intro-card"><div className="intro-top"><span>ROOMRADAR INTRODUCTION</span><strong>{match.score}% <small>MATCH</small></strong></div><div className="intro-names"><div><Avatar p={one} large/><h3>{one.name}</h3><p>{one.role}</p></div><b>×</b><div><Avatar p={two} large/><h3>{two.name}</h3><p>{two.role}</p></div></div><div className="intro-columns"><div><small>{one.name.split(' ')[0].toUpperCase()} CAN HELP {two.name.split(' ')[0].toUpperCase()} WITH</small>{chips(match.youHelp.length?match.youHelp:one.offer.slice(0,2))}</div><div><small>{two.name.split(' ')[0].toUpperCase()} CAN HELP {one.name.split(' ')[0].toUpperCase()} WITH</small>{chips(match.theyHelp.length?match.theyHelp:two.offer.slice(0,2))}</div></div><div className="intro-copy"><small>CONVERSATION OPENER</small><p>{intro(one,match)}</p><small>10-MINUTE CHALLENGE</small><p>Sketch one useful feature {two.name.split(' ')[0]} needs and decide on a small prototype or next introduction together.</p></div><div className="detail-actions"><button className="secondary" onClick={()=>{navigator.clipboard?.writeText(intro(one,match));showToast('Introduction copied to clipboard.')}}>Copy Introduction</button><button className="secondary" onClick={()=>showToast('Connection saved.')}>Save Connection</button><button className="primary" onClick={()=>onOpen(match)}>Open Mutual-Win Card →</button></div></div></section>}
function intro(me,match){ const p=match.person; return `Hey ${p.name.split(' ')[0]}, I saw you're ${p.role.toLowerCase()} and looking for ${p.need.slice(0,2).join(' and ')}. I've been working on ${me.offer.slice(0,2).join(' and ')}. Your work on ${p.goal.toLowerCase()} stood out to me. Want to compare notes for 10 minutes?`; }
function MatchDetail({me,match,onBack,onSave,onCopy,onNew}){const p=match.person;const yourContribution=match.youHelp.length?match.youHelp:p.need.slice(0,2);const theirContribution=match.theyHelp.length?match.theyHelp:p.offer.slice(0,2);const first=p.name.split(' ')[0]; return <section className="detail"><button className="back" onClick={onBack}>← Back to matches</button><div className="win-card"><div className="win-glow"></div><div className="win-head"><div className="match-badge"><strong>{match.score}%</strong><span>MUTUAL MATCH</span></div><div className="pair"><div><Avatar p={me}/><span>{me.name}</span></div><b>×</b><div><Avatar p={p}/><span>{p.name}</span></div></div><span className="live-dot">A high-value room connection</span></div><div className="win-title"><div className="eyebrow"><span></span> YOUR MUTUAL-WIN CARD</div><h2>Why you two<br/><em>should meet.</em></h2><p>You are both building toward the same future, from complementary angles.</p></div><div className="exchange"><div><span>YOU CAN HELP {first.toUpperCase()} WITH</span>{chips(yourContribution)}<p>Your hands-on experience can move their current goal from idea to build.</p></div><div><span>{first.toUpperCase()} CAN HELP YOU WITH</span>{chips(theirContribution)}<p>Their perspective and network can unlock the next step for you.</p></div></div><div className="opportunities"><article><span className="icon">↗</span><div><small>BEST CONVERSATION STARTER</small><p>{intro(me,match)}</p></div></article><article><span className="icon">◷</span><div><small>10-MINUTE OPPORTUNITY</small><p>Spend ten minutes mapping a first version of {p.goal.toLowerCase().replace(/\.$/,'')} and exchange the best next resource.</p></div></article><article><span className="icon">✦</span><div><small>SUGGESTED FOLLOW-UP</small><p>Send {first} a short note tonight with one concrete way you can help and a time to continue the conversation.</p></div></article></div><div className="detail-actions"><button className="secondary" onClick={onCopy}>Copy Intro <span>⧉</span></button><button className="secondary" onClick={onSave}>Save Connection <span>♡</span></button><button className="primary" onClick={onNew}>Find Another Match <span>→</span></button></div></div></section>}
function People({onOpen}){return <section className="people"><div className="eyebrow"><span></span> THE ROOM</div><h2>Meet the <em>people</em> behind the signals.</h2><div className="stats"><div><b>12</b><span>People in room</span></div><div><b>48</b><span>Skills available</span></div><div><b>84</b><span>Opportunities discovered</span></div></div><div className="people-grid">{people.map(p=><button className="person" onClick={()=>onOpen(p)} key={p.id}><Avatar p={p}/><div><strong>{p.name}</strong><span>{p.role}</span>{chips(p.offer.slice(0,2),true)}</div><b>→</b></button>)}</div></section>}
function Saved({saved,onOpen}){const list=people.filter(p=>saved.includes(p.id));return <section className="people saved"><div className="eyebrow"><span></span> YOUR CONNECTIONS</div><h2>Keep the good <em>conversations</em> moving.</h2>{list.length?<div className="people-grid">{list.map(p=><button className="person" onClick={()=>onOpen(p)} key={p.id}><Avatar p={p}/><div><strong>{p.name}</strong><span>{p.role}</span>{chips(p.offer.slice(0,2),true)}</div><b>→</b></button>)}</div>:<div className="empty"><span>♡</span><h3>No saved connections yet</h3><p>When someone stands out, save them here so the conversation does not get lost.</p></div>}</section>}
createRoot(document.getElementById('root')).render(<App/>);
